server:
  port: 8080

logging:
  config: classpath:log4j.xml

spring:
  cache:
    # 缓存类型
    type: caffeine
    # 缓存管理器名称，多个缓存管理器时使用。使用逗号分隔
    cache-names: userInfo
    caffeine:
      # Caffeine配置说明：
      # initialCapacity=[integer]: 初始的缓存空间大小
      # maximumSize=[long]: 缓存的最大条数
      # maximumWeight=[long]: 缓存的最大权重
      # expireAfterAccess=[duration]: 最后一次写入或访问后经过固定时间过期
      # expireAfterWrite=[duration]: 最后一次写入后经过固定时间过期
      # refreshAfterWrite=[duration]: 创建缓存或者最近一次更新缓存后经过固定的时间间隔刷新缓存
      # weakKeys: 打开key的弱引。弱引用的对象拥有更短暂的生命周期。在垃圾回收器线程扫描它所管辖的内存区域的过程中，一旦发现了只具有弱引用的对象，不管当前内存空间足够与否，都会回收它的内存。
      # weakValues: 打开value的弱引用
      # softValues: 打开value的软引用。一个对象只具有软引用时，如果内存空间足够，垃圾回收器就不会回收它；如果内存空间不足了，就会回收这些对象的内存。
      # recordStats: 开发统计功能
      # 注意：
      # 1、expireAfterWrite和expireAfterAccess同时存在时,以expireAfterWrite为准。
      # 2、maximumSize和maximumWeight不可以同时使用。
      # 3、weakValues和softValues不可以同时使用。
      spec: initialCapacity=50,maximumSize=500,expireAfterAccess=5s,expireAfterWrite=10s,refreshAfterWrite=5s
